/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ttaiit.blogspot.com;

import abstr.Node;
import factory.TreeNodeFactory;
import model.Item;
import model.ItemContainer;

import javax.swing.*;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;
import java.util.HashMap;
import java.util.Map;

/**
 *
 * @author Fahad Khan
 * @update [10/28/2018] [Shuhui Wu]
 */
public class AddWindow extends javax.swing.JFrame {

    /**
     * Creates new form AddWindow
     */
    public AddWindow(){}

    public AddWindow(World par)
    {
        initComponents();
        this.parentWindow = par;
        this.newnode = parentWindow.getNewnode();
        this.log = parentWindow.getLog();
        this.logmap = parentWindow.getLogmap();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        tfName = new javax.swing.JTextField();
        tfX = new javax.swing.JTextField();
        tfY = new javax.swing.JTextField();
        tfLength = new javax.swing.JTextField();
        tfWidth = new javax.swing.JTextField();
        tfPrice = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Name");

        jLabel2.setText("Price");

        jLabel3.setText("X-Axis");

        jButton1.setText("Save");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel4.setText("Y-Axis");

        jLabel5.setText("Length");

        jLabel6.setText("Width");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item", "ItemContainer" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addGap(0, 161, Short.MAX_VALUE)
                                                .addComponent(jButton1))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(23, 23, 23)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel1)
                                                        .addComponent(jLabel2)
                                                        .addComponent(jLabel3)
                                                        .addComponent(jLabel4)
                                                        .addComponent(jLabel5)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGap(1, 1, 1)
                                                                .addComponent(jLabel6)))
                                                .addGap(24, 24, 24)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(tfWidth)
                                                        .addComponent(tfLength)
                                                        .addComponent(tfY)
                                                        .addComponent(tfX)
                                                        .addComponent(tfName)
                                                        .addComponent(tfPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(0, 0, Short.MAX_VALUE)))
                                .addContainerGap())
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel1)
                                        .addComponent(tfName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel2)
                                        .addComponent(tfPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel3)
                                        .addComponent(tfX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel4)
                                        .addComponent(tfY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(19, 19, 19)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel5)
                                        .addComponent(tfLength, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel6)
                                        .addComponent(tfWidth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(65, 65, 65)
                                .addComponent(jButton1))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private boolean isDigitString(String s){
        return s.matches("-?[0-9]+\\.?[0-9]*");
    }

    private boolean checkInput(){
        if (!tfName.getText().equals("") &&
                !tfLength.getText().equals("") &&
                !tfPrice.getText().equals("") &&
                !tfWidth.getText().equals("") &&
                !tfX.getText().equals("") &&
                !tfY.getText().equals("")
        )
            if (isDigitString(tfLength.getText()) && isDigitString(tfPrice.getText()) && isDigitString(tfWidth.getText())
                    && isDigitString(tfX.getText()) && isDigitString(tfY.getText()))
                return true;

        return false;
    }

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {  //save
        //GEN-FIRST:event_jButton1ActionPerformed
        Map<String, Object> treenodeInfo = parentWindow.getNodemap();

        if (!checkInput())
            JOptionPane.showMessageDialog(null, "Illegal parameter!");
        else if (treenodeInfo.containsKey(tfName.getText()))
            JOptionPane.showMessageDialog(null, "Cannot add identical name!");
        else {
            TreeNodeFactory tf = new TreeNodeFactory();
            String objtype = (String) jComboBox1.getSelectedItem();
            String name = tfName.getText();
            double price = Double.parseDouble(tfPrice.getText());
            int x = Integer.parseInt(tfX.getText());
            int y = Integer.parseInt(tfY.getText());
            int length = Integer.parseInt(tfLength.getText());
            int width = Integer.parseInt(tfWidth.getText());

            newnode = tf.getInstance((String) jComboBox1.getSelectedItem());
            newnode.initialize(name, price, x, y, width, length);
            parentWindow.setNewnode(newnode);
            treenodeInfo.put(name, (objtype.equals("Item")) ? (Item) newnode : (ItemContainer) newnode);
            JTree tree = parentWindow.getTreeWorld();
            DefaultMutableTreeNode selectedNode = (DefaultMutableTreeNode) tree.getSelectionPath().getLastPathComponent();
            //implement itemlist
            ItemContainer parentnode = (ItemContainer) treenodeInfo.get(selectedNode.toString());
            parentnode.getItemList().add(newnode);
            //add string to tree
            DefaultMutableTreeNode newNode = new DefaultMutableTreeNode(name);
            selectedNode.add(newNode);
            // add to command log
            String logmes = "Add " + objtype + " " + name;
            log.addElement(logmes);
            logmap.put(logmes, new HashMap<>());
            logmap.get(logmes).put("treenode", selectedNode.getLastChild());
            logmap.get(logmes).put("obj", newnode);
            logmap.get(logmes).put("parentnode", selectedNode);
            //refresh tree model
            DefaultTreeModel model = (DefaultTreeModel) tree.getModel();
            model.reload();
            this.dispose();
        }


    }//GEN-LAST:event_jButton1ActionPerformed


    public void NewScreen() {
        this.setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField tfLength;
    private javax.swing.JTextField tfName;
    private javax.swing.JTextField tfPrice;
    private javax.swing.JTextField tfWidth;
    private javax.swing.JTextField tfX;
    private javax.swing.JTextField tfY;
    private Node newnode;
    private World parentWindow;
    private DefaultListModel<String> log;
    private Map<String, Map<String, Object>> logmap;

    public Node getNewnode() {
        return newnode;
    }

    public void setNewnode(Node newnode) {
        this.newnode = newnode;
    }



    // End of variables declaration//GEN-END:variables
}
